name: clas12-env-ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cvmfs-contrib/github-action-cvmfs@v3
        with:
          cvmfs_repositories: 'oasis.opensciencegrid.org'
      - name: install
        run: |
          sudo apt-get install tcl-dev
          wget https://github.com/cea-hpc/modules/releases/download/v5.4.0/modules-5.4.0.tar.gz
          tar -xzf modules-5.4.0.tar.gz
          cd modules-5.4.0 && ./configure --prefix=$PWD/../modules && make && make install
      - name: test-local
        run: |
          . ./modules/init/bash
          module --version
          module use ./modulefiles
          module avail
          for x in ./modulefiles/*; do x=$(basename $x) && module load $x && module list && module unload $x; done
      - name: test-cvmfs
        run: |
          . ./modules/init/bash
          module use /cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/sw/modulefiles
          module avail
          for x in ./modulefiles/*; do x=$(basename $x) && module load $x && module unload $x; done
          module load clas12
          java -version
          which decoder
          decoder -h || true

